### PR TITLE
Fix checksum calculation

### PR DESCRIPTION
**Pull request by qwertymodo**
I'm not sure where you got that 0x01FE from, but this should fix the checksum calculation.

### CODE REVIEW

**Comment by KevinCathcart** [comment]
I believe the checksum calculation is correct as-is, except when run through the VT website. Without this patch, snes9x is reporting correct checksums for all generated files for me. 

The per the SNES Dev manual the correct way to handle checksums is to write 0xFF into bytes 0x7FDC and 0x7FDD and 0x00 into bytes 0x7FDE and 0x7FDF. Then sum all the bytes with a 16 bit accumulator  and rewrite those 4 bytes (with the inverted and normal checksums respectively. ) 

To avoid writing those bytes twice I simply sumed those hardedcoded values (0xFF +0xFF + 0x00 + 0x00) = 0x01FE, and add that in.

**Comment by qwertymodo** [comment]
You misunderstood the point of that step in the manual.  Writing any single pair of a 16-bit value and its inverse has no effect on the final 16-bit checksum (kind of like adding any multiple of 10,000 to a number makes no difference to the last 4 digits).  Writing those specific values to those bytes has the same result as just skipping those 4 bytes when creating the checksum.  You don't need to do both, and the way you're currently doing it isn't correct.  Just remove the +0x01FE and it will be correct.

**Comment by KevinCathcart** [comment]
The checksum works by adding non-sign extended bytes, not 16 bit words. Therefore the checksum and inverse do not cancel out.  Even if you were adding a word at a time a word and its bitwise inverse will would always sum to 0xFFFF (i.e. -1, not 0). 

With the current code snes9X says "[checksum ok]" when loading a rom. If I apply the proposed patch it says "[bad checksum]".

**Comment by qwertymodo** [comment]
Well... this is weird.  I'm really not sure what I did, but you're absolutely right.  This PR should not be included, and I need to change the VT checksum to match.

**Pull request closed without merging**
